VPHI/urls.py
from django.urls import path
from .views import index, sub01, sub02, sub03, sub04, sub05

from . import views

app_name = 'VPHI'

urlpatterns = [
    path('', index.main, name='index'),

    path('sub01/sub01_01', sub01.sub01_01, name='SUB01_01'),

    path('sub02/sub02_01', sub02.sub02_01, name='SUB02_01'),

    path('sub03/sub03_01', sub03.sub03_01, name='SUB03_01'),

    path('sub04/sub04_01', sub04.sub04_01, name='SUB04_01'),
    path('sub04/sub04_02', sub04.sub04_02, name='SUB04_02'),
    path('sub04/sub04_03', sub04.sub04_03, name='SUB04_03'),

    path('sub05/sub05_01', sub05.sub05_01, name='SUB05_01'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('VPHI.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

VPHI/models.py
from django.db import models

# Create your models here.

VPHI/views/index.py
from django.shortcuts import render

# Create your views here.

def main(request):
    return render(request, 'VPHI/index.html')

VPHI/views/sub01.py
from django.shortcuts import render

# Create your views here.

def sub01_01(request):
    return render(request, 'VPHI/sub01/sub01_01.html')

VPHI/views/sub02.py
from django.shortcuts import render

# Create your views here.

def sub02_01(request):
    return render(request, 'VPHI/sub02/sub02_01.html')

VPHI/views/sub03.py
from django.shortcuts import render

# Create your views here.

def sub03_01(request):
    return render(request, 'VPHI/sub03/sub03_01.html')

VPHI/views/sub04.py
from django.shortcuts import render

# Create your views here.

def sub04_01(request):
    return render(request, 'VPHI/sub04/sub04_01.html')

def sub04_02(request):
    return render(request, 'VPHI/sub04/sub04_02.html')

def sub04_03(request):
    return render(request, 'VPHI/sub04/sub04_03.html')

VPHI/views/sub05.py
from django.shortcuts import render

# Create your views here.

def sub05_01(request):
    return render(request, 'VPHI/sub05/sub05_01.html')

templates/VPHI/index.html
{% extends "base.html" %}
{% load static %}


{% block content %}
    <div style="padding: 1%;">
        <div style="border-bottom: 1px solid #D8D8D8; margin-top: 3%">
            <h1>INDEX</h1>
        </div>
    </div>

    <div style="padding: 1%;">
        <div style="border: 1px solid #D8D8D8; width: 100%; height: 300px;">
            <p1>테이블 공간</p1>
        </div>
    </div>



{% endblock content %}

templates/VPHI/sub01/sub01_01.html
{% extends "base.html" %}
{% load static %}


{% block content %}
    <div style="padding: 0.5%;">
        <div>
            <h3 style="border-bottom: 2px solid #D8D8D8; ">SUB01_01</h3>
        </div>
        <div>
            <div style="float: left">
                <button class="btn_blue ripple" type="button">테스트</button>
                <button class="btn_blue ripple" type="button">테스트</button>
            </div>
            <div style="float: right">
                <button class="btn_blue ripple" type="button">테스트</button>
                <button class="btn_blue ripple" type="button">테스트</button>
                <button class="btn_blue ripple" type="button">테스트</button>
            </div>
        </div>
    </div>


    <div style="padding: 0.5%; margin-top: 30px;">
        <div style="border: 2px solid #D8D8D8; width: 100%; height: 10%; display: inline-block; background-color: #F7F7F7">
            <div style="padding: 0.2%">

                <label>테스트</label>
                <input type="text">
                <input type="text">

                <label style="margin-left: 15%">테스트</label>
                <input type="text">
                <input type="text">
            </div>
            <div style="padding: 0.2%">
                <label>테스트</label>
                <input type="text">
                <input type="text">
                <label style="margin-left: 15%">테스트</label>
                <input type="text">
                <input type="text">
            </div>
            <div style="padding: 0.2%">
                <label>테스트</label>
                <input type="text">
                <input type="text">
                <label style="margin-left: 15%">테스트</label>
                <input type="text">
                <input type="text">
            </div>
        </div>
    </div>

    <div style="padding: 0.5%;">
        <div style="border: 1px solid #D8D8D8; width: 100%; height: 700px; overflow-x: auto; overflow-y: auto;">
            <table class="table-wrapper">
                <thead>
                <tr class="colored">
                    <th>TEST</th>
                    <th>TEST</th>
                    <th>TEST</th>
                    <th>TEST</th>
                    <th>TEST</th>
                    <th>TEST</th>
                </tr>
                </thead>
                <tbody>
                <tbody class="tbl-accordion-header">
                <tr class="colored">
                    <td>
                        <a><strong>TEST</strong></a>
                    </td>
                    <td>TEST</td>
                    <td>TEST</td>
                    <td>TEST</td>
                    <td>TEST</td>
                    <td>TEST</td>
                </tr>
                <tr class="colored">
                    <td>
                        <a><strong>TEST</strong></a>
                    </td>
                    <td>TEST</td>
                    <td>TEST</td>
                    <td>TEST</td>
                    <td>TEST</td>
                    <td>TEST</td>
                </tr>
                <tr class="colored">
                    <td>
                        <a><strong>TEST</strong></a>
                    </td>
                    <td>TEST</td>
                    <td>TEST</td>
                    <td>TEST</td>
                    <td>TEST</td>
                    <td>TEST</td>
                </tr>
                <tr class="colored">
                    <td>
                        <a><strong>TEST</strong></a>
                    </td>
                    <td>TEST</td>
                    <td>TEST</td>
                    <td>TEST</td>
                    <td>TEST</td>
                    <td>TEST</td>
                </tr>
                <tr class="colored">
                    <td>
                        <a><strong>TEST</strong></a>
                    </td>
                    <td>TEST</td>
                    <td>TEST</td>
                    <td>TEST</td>
                    <td>TEST</td>
                    <td>TEST</td>
                </tr>
                <tr class="colored">
                    <td>
                        <a><strong>TEST</strong></a>
                    </td>
                    <td>TEST</td>
                    <td>TEST</td>
                    <td>TEST</td>
                    <td>TEST</td>
                    <td>TEST</td>
                </tr>
                <tr class="colored">
                    <td>
                        <a><strong>TEST</strong></a>
                    </td>
                    <td>TEST</td>
                    <td>TEST</td>
                    <td>TEST</td>
                    <td>TEST</td>
                    <td>TEST</td>
                </tr>
                <tr class="colored">
                    <td>
                        <a><strong>TEST</strong></a>
                    </td>
                    <td>TEST</td>
                    <td>TEST</td>
                    <td>TEST</td>
                    <td>TEST</td>
                    <td>TEST</td>
                </tr>
                <tr class="colored">
                    <td>
                        <a><strong>TEST</strong></a>
                    </td>
                    <td>TEST</td>
                    <td>TEST</td>
                    <td>TEST</td>
                    <td>TEST</td>
                    <td>TEST</td>
                </tr>
                <tr class="colored">
                    <td>
                        <a><strong>TEST</strong></a>
                    </td>
                    <td>TEST</td>
                    <td>TEST</td>
                    <td>TEST</td>
                    <td>TEST</td>
                    <td>TEST</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div style="padding: 0.5%;">
        <div style="border: 1px solid black; width: 100%; background-color: #92B4EC">
            <div style="padding: 0.5%">
                <label>테스트</label>
                <input class="input_width" type="text"/>
                <input class="input_width" type="text"/>
                <input class="input_width" type="text"/>

                <input id="text_red" class="input_width" style="float: right;" type="text" value="33,000"/>
                <label style="float: right">테스트</label>
                <input class="input_width" style="float: right;" type="text" value="3,000"/>
                <label style="float: right">테스트</label>
                <input class="input_width" style="float: right" type="text" value="15,000"/>
                <label style="float: right">테스트</label>
            </div>
        </div>
    </div>


    <div style="padding: 0.5%;">
        <div style="width: 100%; display: inline-block;">
            <div style="border: 2px solid black; width: 49%; height: 150px; float: left; overflow-x: auto; overflow-y: auto">
                <table class="table-wrapper">
                    <thead>
                    <tr class="colored">
                        <th>TEST</th>
                        <th>TEST</th>
                        <th>TEST</th>
                        <th>TEST</th>
                        <th>TEST</th>
                        <th>TEST</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tbody class="tbl-accordion-header">
                    <tr class="colored">
                        <td>
                            <a><strong>TEST</strong></a>
                        </td>
                        <td>TEST</td>
                        <td>TEST</td>
                        <td>TEST</td>
                        <td>TEST</td>
                        <td>TEST</td>
                    </tr>
                    <tr class="colored">
                        <td>
                            <a><strong>TEST</strong></a>
                        </td>
                        <td>TEST</td>
                        <td>TEST</td>
                        <td>TEST</td>
                        <td>TEST</td>
                        <td>TEST</td>
                    </tr>
                    <tr class="colored">
                        <td>
                            <a><strong>TEST</strong></a>
                        </td>
                        <td>TEST</td>
                        <td>TEST</td>
                        <td>TEST</td>
                        <td>TEST</td>
                        <td>TEST</td>
                    </tr>
                    </tbody>
                </table>
            </div>

            <div style="border: 2px solid black; width: 49%; height: 150px; float: right; overflow-y: auto; overflow-x: auto">
                <table class="table-wrapper">
                    <thead>
                    <tr class="colored">
                        <th>TEST</th>
                        <th>TEST</th>
                        <th>TEST</th>
                        <th>TEST</th>
                        <th>TEST</th>
                        <th>TEST</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tbody class="tbl-accordion-header">
                    <tr class="colored">
                        <td>
                            <a><strong>TEST</strong></a>
                        </td>
                        <td>TEST</td>
                        <td>TEST</td>
                        <td>TEST</td>
                        <td>TEST</td>
                        <td>TEST</td>
                    </tr>
                    <tr class="colored">
                        <td>
                            <a><strong>TEST</strong></a>
                        </td>
                        <td>TEST</td>
                        <td>TEST</td>
                        <td>TEST</td>
                        <td>TEST</td>
                        <td>TEST</td>
                    </tr>
                    <tr class="colored">
                        <td>
                            <a><strong>TEST</strong></a>
                        </td>
                        <td>TEST</td>
                        <td>TEST</td>
                        <td>TEST</td>
                        <td>TEST</td>
                        <td>TEST</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}

templates/VPHI/sub02/sub02_01.html
{% extends "base.html" %}
{% load static %}


{% block content %}
    <div style="padding: 1%;">
        <div style="border-bottom: 1px solid #D8D8D8; margin-top: 3%">
            <h1>SUB02_01</h1>
        </div>
    </div>

    <div style="padding: 1%;">
        <div style="border: 1px solid #D8D8D8; width: 100%; height: 300px;">
            <p1>테이블 공간</p1>
        </div>
    </div>



{% endblock content %}

templates/VPHI/sub03/sub03_01.html
{% extends "base.html" %}
{% load static %}


{% block content %}
    <div style="padding: 1%;">
        <div style="border-bottom: 1px solid #D8D8D8; margin-top: 3%">
            <h1>SUB03_01</h1>
        </div>
    </div>

    <div style="padding: 1%;">
        <div style="border: 1px solid #D8D8D8; width: 100%; height: 300px;">
            <p1>테이블 공간</p1>
        </div>
    </div>



{% endblock content %}

templates/VPHI/sub04/sub04_01.html
{% extends "base.html" %}
{% load static %}


{% block content %}
    <div style="padding: 1%;">
        <div style="border-bottom: 1px solid #D8D8D8; margin-top: 3%">
            <h1>SUB04_01</h1>
        </div>
    </div>

    <div style="padding: 1%;">
        <div style="border: 1px solid #D8D8D8; width: 100%; height: 300px;">
            <p1>테이블 공간</p1>
        </div>
    </div>



{% endblock content %}

templates/VPHI/sub04/sub04_02.html
{% extends "base.html" %}
{% load static %}


{% block content %}
    <div style="padding: 1%;">
        <div style="border-bottom: 1px solid #D8D8D8; margin-top: 3%">
            <h1>SUB04_02</h1>
        </div>
    </div>

    <div style="padding: 1%;">
        <div style="border: 1px solid #D8D8D8; width: 100%; height: 300px;">
            <p1>테이블 공간</p1>
        </div>
    </div>



{% endblock content %}

templates/VPHI/sub04/sub04_03.html
{% extends "base.html" %}
{% load static %}


{% block content %}
    <div style="padding: 1%;">
        <div style="border-bottom: 1px solid #D8D8D8; margin-top: 3%">
            <h1>SUB04_03</h1>
        </div>
    </div>

    <div style="padding: 1%;">
        <div style="border: 1px solid #D8D8D8; width: 100%; height: 300px;">
            <p1>테이블 공간</p1>
        </div>
    </div>



{% endblock content %}

templates/VPHI/sub05/sub05_01.html
{% extends "base.html" %}
{% load static %}


{% block content %}
    <div style="padding: 1%;">
        <div style="border-bottom: 1px solid #D8D8D8; margin-top: 3%">
            <h1>SUB05_01</h1>
        </div>
    </div>

    <div style="padding: 1%;">
        <div style="border: 1px solid #D8D8D8; width: 100%; height: 300px;">
            <p1>테이블 공간</p1>
        </div>
    </div>



{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="{% static 'css/style.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/content.css' %}" rel="stylesheet"/>
    <script src="{% static 'js/scripts.js' %}"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>


</head>
<body>
<header>
    {% include 'header.html' %}
</header>
<main>
    {% include 'navbar.html' %}
    {% block content %}
        {#        내용#}
    {% endblock %}
    {% block script %}
        {#        스크립트#}
    {% endblock %}
</main>
</body>
</html>

templates/header.html
<div class="mainmenu">

    <ul>
        <li class="li_nc"><a href="/" target="_self">
            <img style="height: 40px; margin-top: 5px" src="http://www.phcvaleo-webcat.com/eng/_include/image/common/logo.jpg"/>
        </a></li>
        <div style="float: right; margin-top: 15px;">
            <li class="li_nc"><a href="/" target="_self">
                <i style="color: #396EB0" class="fa-solid fa-user"></i>
            </a></li>
            <li class="li_nc"><a href="/" target="_self"><i style="color: #396EB0" class="fa-solid fa-magnifying-glass"></i></a></li>
        </div>
    </ul>


</div>

templates/navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body id="body-pd">
<div class="l-navbar" id="navbar">
    <nav class="nav">
        <div>
            <div class="nav__brand">
                <ion-icon name="menu-outline" class="nav__toggle" id="nav-toggle"></ion-icon>
                <a href="#" class="nav__logo"></a>
            </div>
            <div class="nav__list">
                <a href="{% url 'VPHI:SUB01_01' %}" class="nav__link active">
                    <ion-icon name="home-outline" class="nav__icon"></ion-icon>
                    <span class="nav__name">메인</span>
                </a>
                <a href="{% url 'VPHI:SUB02_01' %}" class="nav__link">
                    <ion-icon name="chatbubbles-outline" class="nav__icon"></ion-icon>
                    <span class="nav__name">게시판</span>
                </a>


                <a href="{% url 'VPHI:SUB03_01' %}" class="nav__link">
                    <ion-icon name="pie-chart-outline" class="nav__icon"></ion-icon>
                    <span class="nav__name">통계</span>
                </a>
                <div id="menu_link" class="nav__link collapse">
                    <ion-icon name="people-outline" class="nav__icon"></ion-icon>
                    <span class="nav__name">물류</span>

                    <ion-icon name="chevron-down-outline" class="collapse__link"></ion-icon>

                    <ul class="collapse__menu">
                        <a href="{% url 'VPHI:SUB04_01' %}" class="collapse__sublink">TEST</a>
                        <a href="{% url 'VPHI:SUB04_02' %}" class="collapse__sublink">TEST</a>
                        <a href="{% url 'VPHI:SUB04_03' %}" class="collapse__sublink">TEST</a>
                    </ul>
                </div>
                <a href="{% url 'VPHI:SUB05_01' %}" class="nav__link">
                    <ion-icon name="settings-outline" class="nav__icon"></ion-icon>
                    <span class="nav__name">설정</span>
                </a>
            </div>
        </div>

        {#        <a href="#" class="nav__link">#}
        {#            <ion-icon name="log-out-outline" class="nav__icon"></ion-icon>#}
        {#            <span class="nav__name">Log Out</span>#}
        {#        </a>#}
    </nav>
</div>
<!-- ===== IONICONS ===== -->
</body>
<script src="https://unpkg.com/ionicons@5.1.2/dist/ionicons.js"></script>

<script>
    /*===== EXPANDER MENU  =====*/
    const showMenu = (toggleId, navbarId, bodyId) => {
        const toggle = document.getElementById(toggleId),
            navbar = document.getElementById(navbarId),
            bodypadding = document.getElementById(bodyId)

        if (toggle && navbar) {
            toggle.addEventListener('click', () => {

                navbar.classList.toggle('expander')

                bodypadding.classList.toggle('body-pd')
            })
        }
    }
    showMenu('nav-toggle', 'navbar', 'body-pd')


    /*===== LINK ACTIVE  =====*/
    const linkColor = document.querySelectorAll('.nav__link')

    function colorLink() {
        linkColor.forEach(l => l.classList.remove('active'))
        this.classList.add('active')
    }

    linkColor.forEach(l => l.addEventListener('click', colorLink))


    /*===== COLLAPSE MENU  =====*/
    const linkCollapse = document.getElementsByClassName('collapse__link')
    var i

    for (i = 0; i < linkCollapse.length; i++) {
        linkCollapse[i].addEventListener('click', function () {
            const collapseMenu = this.nextElementSibling
            collapseMenu.classList.toggle('showCollapse')

            const rotate = collapseMenu.previousElementSibling
            rotate.classList.toggle('rotate')
        })
    }


</script>

</html>